server:
  servlet:
    encoding:
      force-response: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource :
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/likelion-db
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: update
jwt:
  secret: "secretKey"